<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'employee_code' => 'EMP001',
                'name' => 'Ahmad Kurniawan',
                'position' => 'Manager',
                'phone' => '081234567890',
                'email' => 'ahmad.kurniawan@aghitsna.com',
                'address' => 'Jl. Merdeka No. 123, Jakarta',
                'base_salary' => 8000000,
                'join_date' => '2020-01-15',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP002',
                'name' => 'Siti Nurhaliza',
                'position' => 'Supervisor',
                'phone' => '081234567891',
                'email' => 'siti.nurhaliza@aghitsna.com',
                'address' => 'Jl. Sudirman No. 45, Jakarta',
                'base_salary' => 6000000,
                'join_date' => '2020-06-01',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP003',
                'name' => 'Budi Santoso',
                'position' => 'Staff Administrasi',
                'phone' => '081234567892',
                'email' => 'budi.santoso@aghitsna.com',
                'address' => 'Jl. Gatot Subroto No. 78, Jakarta',
                'base_salary' => 4500000,
                'join_date' => '2021-03-10',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP004',
                'name' => 'Dewi Lestari',
                'position' => 'Staff Marketing',
                'phone' => '081234567893',
                'email' => 'dewi.lestari@aghitsna.com',
                'address' => 'Jl. Thamrin No. 90, Jakarta',
                'base_salary' => 5000000,
                'join_date' => '2021-07-20',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP005',
                'name' => 'Eko Prasetyo',
                'position' => 'Staff Produksi',
                'phone' => '081234567894',
                'email' => 'eko.prasetyo@aghitsna.com',
                'address' => 'Jl. Asia Afrika No. 12, Jakarta',
                'base_salary' => 4000000,
                'join_date' => '2022-01-05',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP006',
                'name' => 'Fitri Handayani',
                'position' => 'Staff Keuangan',
                'phone' => '081234567895',
                'email' => 'fitri.handayani@aghitsna.com',
                'address' => 'Jl. Kemang Raya No. 34, Jakarta',
                'base_salary' => 5500000,
                'join_date' => '2022-04-15',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP007',
                'name' => 'Gunawan Wijaya',
                'position' => 'Driver',
                'phone' => '081234567896',
                'email' => 'gunawan.wijaya@aghitsna.com',
                'address' => 'Jl. Raya Bogor No. 56, Jakarta',
                'base_salary' => 3500000,
                'join_date' => '2022-08-01',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP008',
                'name' => 'Hendra Gunawan',
                'position' => 'Staff IT',
                'phone' => '081234567897',
                'email' => 'hendra.gunawan@aghitsna.com',
                'address' => 'Jl. Rasuna Said No. 89, Jakarta',
                'base_salary' => 6500000,
                'join_date' => '2023-02-10',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP009',
                'name' => 'Indah Permatasari',
                'position' => 'Staff HRD',
                'phone' => '081234567898',
                'email' => 'indah.permatasari@aghitsna.com',
                'address' => 'Jl. Kuningan No. 23, Jakarta',
                'base_salary' => 5000000,
                'join_date' => '2023-06-01',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP010',
                'name' => 'Joko Widodo',
                'position' => 'Security',
                'phone' => '081234567899',
                'email' => 'joko.widodo@aghitsna.com',
                'address' => 'Jl. Pancoran No. 67, Jakarta',
                'base_salary' => 3000000,
                'join_date' => '2023-09-15',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP011',
                'name' => 'Kartika Sari',
                'position' => 'Staff Gudang',
                'phone' => '081234567800',
                'email' => null,
                'address' => 'Jl. Cikini No. 45, Jakarta',
                'base_salary' => 3800000,
                'join_date' => '2024-01-10',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP012',
                'name' => 'Lukman Hakim',
                'position' => 'Staff Produksi',
                'phone' => '081234567801',
                'email' => null,
                'address' => null,
                'base_salary' => 4000000,
                'join_date' => '2024-05-20',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP013',
                'name' => 'Maya Putri',
                'position' => 'Receptionist',
                'phone' => null,
                'email' => 'maya.putri@aghitsna.com',
                'address' => 'Jl. Senopati No. 78, Jakarta',
                'base_salary' => 3500000,
                'join_date' => '2024-08-01',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP014',
                'name' => 'Nugroho Adi',
                'position' => 'Staff Maintenance',
                'phone' => '081234567803',
                'email' => null,
                'address' => 'Jl. Tebet No. 90, Jakarta',
                'base_salary' => 4200000,
                'join_date' => '2024-10-15',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP015',
                'name' => 'Rina Wati',
                'position' => 'Staff Cleaning Service',
                'phone' => null,
                'email' => null,
                'address' => null,
                'base_salary' => 2800000,
                'join_date' => '2025-01-05',
                'status' => 'non-aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('employees')->insert($employees);
    }
}
