<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'employee_code' => 'EMP001',
                'name' => 'Ahmad Kurniawan',
                'phone' => '081234567890',
                'address' => 'Jl. Merdeka No. 123, Jakarta',
                'division' => 'Produksi',
                'daily_wage' => 150000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP002',
                'name' => 'Siti Nurhaliza',
                'phone' => '081234567891',
                'address' => 'Jl. Sudirman No. 45, Jakarta',
                'division' => 'Produksi',
                'daily_wage' => 140000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP003',
                'name' => 'Budi Santoso',
                'phone' => '081234567892',
                'address' => 'Jl. Gatot Subroto No. 78, Jakarta',
                'division' => 'Produksi',
                'daily_wage' => 130000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP004',
                'name' => 'Dewi Lestari',
                'phone' => '081234567893',
                'address' => 'Jl. Thamrin No. 90, Jakarta',
                'division' => 'Pemasaran',
                'daily_wage' => 135000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP005',
                'name' => 'Eko Prasetyo',
                'phone' => '081234567894',
                'address' => 'Jl. Asia Afrika No. 12, Jakarta',
                'division' => 'Produksi',
                'daily_wage' => 125000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP006',
                'name' => 'Fitri Handayani',
                'phone' => '081234567895',
                'address' => 'Jl. Kemang Raya No. 34, Jakarta',
                'division' => 'Keuangan',
                'daily_wage' => 145000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP007',
                'name' => 'Gunawan Wijaya',
                'phone' => '081234567896',
                'address' => 'Jl. Raya Bogor No. 56, Jakarta',
                'division' => 'Gudang',
                'daily_wage' => 120000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP008',
                'name' => 'Hendra Gunawan',
                'phone' => '081234567897',
                'address' => 'Jl. Rasuna Said No. 89, Jakarta',
                'division' => 'Administrasi',
                'daily_wage' => 155000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP009',
                'name' => 'Indah Permatasari',
                'phone' => '081234567898',
                'address' => 'Jl. Kuningan No. 23, Jakarta',
                'division' => 'Administrasi',
                'daily_wage' => 135000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP010',
                'name' => 'Joko Widodo',
                'phone' => '081234567899',
                'address' => 'Jl. Pancoran No. 67, Jakarta',
                'division' => 'Gudang',
                'daily_wage' => 110000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP011',
                'name' => 'Kartika Sari',
                'phone' => '081234567800',
                'address' => 'Jl. Cikini No. 45, Jakarta',
                'division' => 'Gudang',
                'daily_wage' => 128000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP012',
                'name' => 'Lukman Hakim',
                'phone' => '081234567801',
                'address' => 'Jl. Matraman No. 88, Jakarta',
                'division' => 'Produksi',
                'daily_wage' => 130000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP013',
                'name' => 'Maya Putri',
                'phone' => '081234567802',
                'address' => 'Jl. Senopati No. 78, Jakarta',
                'division' => 'Pemasaran',
                'daily_wage' => 125000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP014',
                'name' => 'Nugroho Adi',
                'phone' => '081234567803',
                'address' => 'Jl. Tebet No. 90, Jakarta',
                'division' => 'Keuangan',
                'daily_wage' => 138000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_code' => 'EMP015',
                'name' => 'Rina Wati',
                'phone' => '081234567804',
                'address' => 'Jl. Cempaka Putih No. 22, Jakarta',
                'division' => 'Administrasi',
                'daily_wage' => 105000,
                'position' => null,
                'email' => null,
                'base_salary' => null,
                'join_date' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('employees')->insert($employees);
    }
}
