<?php

namespace App\Models\Report;

use App\Models\Report\TransactionCategory;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ExpenseReport extends Model
{
    use HasFactory;

    protected $primaryKey = 'id';
    public $incrementing = false;
    protected $keyType = 'string';

    protected $fillable = [
        'id',
        'transaction_category_id',
        'invoice_number',
        'transaction_date',
        'description',
        'income_amount',
        'expense_amount',
        'money_source',
        'sales_report_id',
        'created_by',
        'notes',
    ];

    protected $casts = [
        'transaction_date' => 'date',
        'income_amount' => 'integer',
        'expense_amount' => 'integer',
    ];

    /**
     * Boot method untuk auto-generate ID
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (empty($model->id)) {
                $model->id = generateExpenseReportId();
            }
        });
    }

    /**
     * Relationship: Category
     */
    public function category()
    {
        return $this->belongsTo(TransactionCategory::class, 'transaction_category_id');
    }

    /**
     * Relationship: Sales Report (untuk transaksi dari penjualan)
     */
    public function salesReport()
    {
        return $this->belongsTo(\App\Models\Report\SalesReport::class, 'sales_report_id', 'id_sales_report');
    }

    /**
     * Relationship: User yang create (untuk manual input)
     */
    public function creator()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Check if this is auto-generated from sales report
     */
    public function isAutoGenerated()
    {
        return !is_null($this->sales_report_id) && is_null($this->created_by);
    }

    /**
     * Check if this is manual input
     */
    public function isManualInput()
    {
        return !is_null($this->created_by);
    }

    /**
     * Scope: Filter by category
     */
    public function scopeByCategory($query, $categoryId)
    {
        return $query->where('transaction_category_id', $categoryId);
    }

    /**
     * Scope: Filter by date range
     */
    public function scopeDateRange($query, $startDate, $endDate)
    {
        return $query->whereBetween('transaction_date', [$startDate, $endDate]);
    }

    /**
     * Scope: Filter by month and year
     */
    public function scopeMonthYear($query, $month, $year)
    {
        return $query->whereMonth('transaction_date', $month)
            ->whereYear('transaction_date', $year);
    }

    /**
     * Scope: Income only
     */
    public function scopeIncome($query)
    {
        return $query->whereNotNull('income_amount')
            ->where('income_amount', '>', 0);
    }

    /**
     * Scope: Expense only
     */
    public function scopeExpense($query)
    {
        return $query->whereNotNull('expense_amount')
            ->where('expense_amount', '>', 0);
    }
}
