<?php

namespace App\Models\Report;

use App\Models\Report\SalesRecap;
use App\Models\Report\TransactionCategory;
use App\Services\Finance\RecapExpenseService;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Model ExpenseRecap.
 *
 * Merepresentasikan data rekap pengeluaran divisi produksi.
 * Setiap record bisa berupa input manual atau auto-generated dari sales recap.
 *
 * Table: expense_recaps
 * Primary Key: id (string, format: RE-00001)
 *
 * @property string $id
 * @property int    $transaction_category_id
 * @property string $invoice_number
 * @property string $transaction_date
 * @property string $description
 * @property int    $income_amount
 * @property int    $expense_amount
 * @property string $money_source
 * @property string $sales_recap_id
 * @property string $created_by
 * @property string $notes
 */
class ExpenseRecap extends Model
{
    use HasFactory;

    protected $table = 'expense_recaps';
    protected $primaryKey = 'id';
    public $incrementing = false;
    protected $keyType = 'string';

    protected $fillable = [
        'id',
        'transaction_category_id',
        'invoice_number',
        'transaction_date',
        'description',
        'income_amount',
        'expense_amount',
        'money_source',
        'sales_recap_id',
        'created_by',
        'notes',
    ];

    protected $casts = [
        'transaction_date' => 'date',
        'income_amount' => 'integer',
        'expense_amount' => 'integer',
    ];

    /**
     * Boot method untuk auto-generate ID saat creating.
     *
     * ID di-generate oleh RecapExpenseService::generateId() yang sudah
     * menggunakan lockForUpdate() untuk mencegah race condition.
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            if (empty($model->id)) {
                $model->id = app(RecapExpenseService::class)->generateId();
            }
        });
    }

    /**
     * Relationship: Kategori transaksi terkait.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(TransactionCategory::class, 'transaction_category_id');
    }

    /**
     * Relationship: Rekap penjualan terkait (jika auto-generated).
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function salesRecap(): BelongsTo
    {
        return $this->belongsTo(SalesRecap::class, 'sales_recap_id', 'id_sales_recap');
    }

    /**
     * Relationship: User yang membuat record (untuk manual input).
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Cek apakah record ini auto-generated dari sales recap.
     *
     * Record auto-generated ditandai dengan sales_recap_id terisi (independen
     * dari created_by). created_by ikut dicatat agar ownership data jelas:
     * rekap otomatis hanya tampil untuk user pemilik (user yang memicu status
     * Lunas), bukan untuk semua user.
     *
     * @return bool
     */
    public function isAutoGenerated(): bool
    {
        return !is_null($this->sales_recap_id);
    }

    /**
     * Cek apakah record ini diinput manual oleh user.
     *
     * @return bool
     */
    public function isManualInput(): bool
    {
        return is_null($this->sales_recap_id) && !is_null($this->created_by);
    }

    /**
     * Scope: Filter berdasarkan kategori transaksi.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     * @param  int                                    $categoryId
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeByCategory($query, int $categoryId)
    {
        return $query->where('transaction_category_id', $categoryId);
    }

    /**
     * Scope: Filter berdasarkan rentang tanggal.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     * @param  string                                 $startDate
     * @param  string                                 $endDate
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeDateRange($query, string $startDate, string $endDate)
    {
        return $query->whereBetween('transaction_date', [$startDate, $endDate]);
    }

    /**
     * Scope: Filter berdasarkan bulan dan tahun.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     * @param  int                                    $month
     * @param  int                                    $year
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeMonthYear($query, int $month, int $year)
    {
        return $query->whereMonth('transaction_date', $month)
            ->whereYear('transaction_date', $year);
    }

    /**
     * Scope: Filter hanya record yang memiliki income_amount > 0.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeIncome($query)
    {
        return $query->whereNotNull('income_amount')
            ->where('income_amount', '>', 0);
    }

    /**
     * Scope: Filter hanya record yang memiliki expense_amount > 0.
     *
     * @param  \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeExpense($query)
    {
        return $query->whereNotNull('expense_amount')
            ->where('expense_amount', '>', 0);
    }
}
