{{-- Expense Report Table Component --}}
<form id="deleteForm" method="POST" action="{{ route('expense-report.destroySelected') }}">
    @csrf
    @method('DELETE')
    <div class="overflow-x-auto -mx-4 px-4 sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="inline-block min-w-full align-middle">
            <div class="border-2 border-border-strong rounded-xl overflow-hidden shadow-sm">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gradient-to-r from-gray-50 to-gray-100">
                        <tr>
                            <th class="p-2 text-center"><input type="checkbox" id="selectAll"></th>
                            <th class="p-2 text-center">ID</th>
                            <th class="p-2 text-left">Kategori</th>
                            <th class="p-2 text-left">Tanggal</th>
                            <th class="p-2 text-left">Faktur</th>
                            <th class="p-2 text-left">Keterangan</th>
                            <th class="p-2 text-right">Pemasukan</th>
                            <th class="p-2 text-right">Pengeluaran</th>
                            <th class="p-2 text-left">Sumber Uang</th>
                            <th class="p-2 text-center">Sumber Data</th>
                            <th class="p-2 text-center">Aksi</th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        @forelse($expenseReports as $expense)
                            <tr class="hover:bg-surface-secondary transition-colors duration-150">
                                <td class="p-2 text-center">
                                    @if (!$expense->isAutoGenerated())
                                        <input type="checkbox" name="selected_expenses[]" value="{{ $expense->id }}"
                                            class="w-4 h-4 accent-primary cursor-pointer">
                                    @endif
                                </td>
                                <td class="p-2 text-center font-medium text-primary">
                                    {{ $expense->id }}
                                </td>
                                <td class="p-2">
                                    <span
                                        class="inline-block px-2 py-1 text-xs font-semibold rounded-lg text-center whitespace-normal break-words max-w-[150px] sm:max-w-none
                                        {{ $expense->category->type == 'INCOME' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700' }}">
                                        {{ $expense->category->name }}
                                    </span>
                                </td>
                                <td class="p-2">
                                    {{ $expense->transaction_date ? \Carbon\Carbon::parse($expense->transaction_date)->format('d/m/Y') : '-' }}
                                </td>
                                <td class="p-2 text-text-label">
                                    {{ $expense->invoice_number ?? '-' }}
                                </td>
                                <td class="p-2 text-text-primary">
                                    {{ $expense->description ?? '-' }}
                                </td>
                                <td
                                    class="p-2 text-right font-medium {{ $expense->income_amount ? 'text-success' : 'text-text-tertiary' }}">
                                    {{ $expense->income_amount ? 'Rp ' . number_format($expense->income_amount, 0, ',', '.') : '-' }}
                                </td>
                                <td
                                    class="p-2 text-right font-medium {{ $expense->expense_amount ? 'text-error' : 'text-text-tertiary' }}">
                                    {{ $expense->expense_amount ? 'Rp ' . number_format($expense->expense_amount, 0, ',', '.') : '-' }}
                                </td>
                                <td class="p-2 text-text-label">
                                    {{ $expense->money_source ?? '-' }}
                                </td>
                                <td class="p-2 text-center">
                                    @if ($expense->isAutoGenerated())
                                        <span
                                            class="inline-flex items-center px-2 py-1 text-xs font-semibold rounded-full bg-primary-light text-primary gap-1">
                                            <i class="fa-solid fa-robot"></i>
                                            Auto
                                        </span>
                                    @else
                                        <span
                                            class="inline-flex items-center px-2 py-1 text-xs font-semibold rounded-full bg-blue-100 text-blue-700 gap-1">
                                            <i class="fa-solid fa-user"></i>
                                            Manual
                                        </span>
                                    @endif
                                </td>
                                <td class="p-2 text-center">
                                    @if (!$expense->isAutoGenerated())
                                        <div class="flex justify-center">
                                            <button type="button" onclick="openModal('editModal-{{ $expense->id }}')"
                                                class="flex items-center justify-center gap-2 bg-btn-edit hover:bg-btn-edit-hover text-white px-3 py-1 rounded-lg transition-colors duration-200">
                                                <i class="fa-solid fa-pen w-4 h-4"></i>
                                                Edit
                                            </button>
                                        </div>
                                    @else
                                        <span class="text-text-tertiary text-sm">
                                            <i class="fa-solid fa-lock"></i>
                                        </span>
                                    @endif
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="11" class="text-center p-4 text-text-secondary">Data tidak ditemukan.</td>
                            </tr>
                        @endforelse

                        {{-- Grand Total Row --}}
                        @if ($expenseReports->isNotEmpty())
                            <tr
                                class="bg-gradient-to-r from-primary/20 to-primary/10 border-t-4 border-primary font-bold text-base">
                                <td colspan="6" class="p-3 text-right text-text-heading">
                                    TOTAL KESELURUHAN
                                </td>
                                <td class="p-3 text-right text-success font-bold text-lg">
                                    Rp {{ number_format($totals->total_income ?? 0, 0, ',', '.') }}
                                </td>
                                <td class="p-3 text-right text-error font-bold text-lg">
                                    Rp {{ number_format($totals->total_expense ?? 0, 0, ',', '.') }}
                                </td>
                                <td colspan="3" class="p-3">
                                    <div class="text-right">
                                        <span class="text-text-primary">Saldo: </span>
                                        <span
                                            class="font-bold text-lg {{ $totals->balance >= 0 ? 'text-success' : 'text-error' }}">
                                            Rp {{ number_format($totals->balance, 0, ',', '.') }}
                                        </span>
                                    </div>
                                </td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</form>
