{{-- Modal Edit Rekap Proyek + Transaksi Laporan Keuangan Proyek (satu design) --}}
@props(['recap', 'categories', 'executives' => collect()])

@php
    $report = $recap->financialReport;
    $existingItems = optional($report)->items ?? collect();

    $executiveOptions = $executives->map(fn ($executive) => [
        'value' => $executive->id,
        'label' => $executive->name.($executive->position ? ' - '.$executive->position : ''),
    ])->values();

    $reportSignatures = app(\App\Services\Report\ProjectFinancialReportService::class)
        ->getReportSignatures($report);

    $categoriesJson = $categories->map(fn ($cat) => [
        'id' => $cat->id,
        'name' => $cat->name,
        'type' => $cat->type,
    ])->values()->toJson();

    $existingItemsJson = $existingItems->map(fn ($item) => [
        'id' => $item->id,
        'payment_proof_id' => $item->payment_proof_id,
        'is_auto' => $item->isAutoGenerated(),
        'auto_source' => str_starts_with((string) $item->description, 'Upah Kerja')
            ? 'payroll'
            : (str_starts_with((string) $item->description, 'Kasbon Divisi') ? 'kasbon' : null),
        'transaction_category_id' => $item->transaction_category_id,
        'transaction_date' => $item->transaction_date ? \Carbon\Carbon::parse($item->transaction_date)->format('Y-m-d') : '',
        'description' => $item->description,
        'amount' => (int) ($item->income_amount ?: $item->expense_amount),
        'keterangan_bon' => $item->keterangan_bon,
        'proof_file' => $item->proof_file,
        'proof_file_name' => $item->proof_file_name,
        'proof_url' => $item->proof_file ? asset('storage/' . $item->proof_file) : null,
    ])->values()->toJson();
@endphp

<x-modal id="editPfrModal-{{ $recap->id }}" title="Edit — {{ $recap->project_name }}"
    action="{{ route('project-financial-report.update', $recap) }}" method="PUT" buttonText="Update"
    enctype="multipart/form-data" size="4xl">

    {{-- ==================== Data Rekap Proyek ==================== --}}
    <h6 class="text-text-primary font-semibold mb-3">Data Rekap Proyek</h6>

    {{-- Nama Proyek --}}
    <div class="mb-3">
        <label class="block text-text-primary mb-1">Nama Proyek <span class="text-error">*</span></label>
        <input type="text" name="project_name" class="w-full border rounded p-2" value="{{ $recap->project_name }}"
            required maxlength="255" oninvalid="this.setCustomValidity('Nama proyek tidak boleh kosong')"
            oninput="this.setCustomValidity('')">
    </div>

    {{-- Lokasi --}}
    <div class="mb-3">
        <label class="block text-text-primary mb-1">Lokasi</label>
        <input type="text" name="location" class="w-full border rounded p-2" value="{{ $recap->location }}"
            maxlength="255">
    </div>

    {{-- Total RAB --}}
    <div class="mb-3">
        <label class="block text-text-primary mb-1">Total RAB <span class="text-error">*</span></label>

        @if ($recap->rab_number)
            <input type="text" class="w-full border rounded p-2 bg-surface-secondary text-text-secondary"
                value="{{ number_format($recap->rab?->total_amount ?? $recap->total_rab ?? 0, 0, ',', '.') }}"
                readonly disabled>
            <input type="hidden" name="total_rab"
                value="{{ $recap->rab?->total_amount ?? $recap->total_rab ?? 0 }}">
            <p class="text-xs text-text-secondary mt-1">
                <i class="fa-solid fa-lock"></i> Total RAB mengikuti RAB sumber
                ({{ $recap->rab_number }}). Ubah di modul RAB.
            </p>
        @else
            <input type="text" inputmode="numeric" name="total_rab" class="w-full border rounded p-2 total-rab-input"
                value="{{ number_format($recap->total_rab ?? 0, 0, ',', '.') }}" required min="0"
                oninvalid="this.setCustomValidity('Total RAB tidak boleh kosong')"
                oninput="this.setCustomValidity('')">
        @endif
    </div>

    {{-- File Design Saat Ini --}}
    @if ($recap->hasDesignFile())
        <div class="mb-3 p-3 border rounded bg-blue-50">
            <label class="block text-text-primary mb-1">File Saat Ini</label>
            <a href="{{ asset('storage/' . $recap->design_file) }}" target="_blank"
                class="text-blue-600 hover:underline text-sm">{{ $recap->design_file_name }}</a>
        </div>
    @endif

    <hr class="my-4">

    {{-- ==================== Detail Transaksi (Struktur Dinamis) ==================== --}}
    <div class="mb-3">
        <h6 class="text-text-primary font-semibold mb-3">Detail Transaksi (Pilih Kategori)</h6>
        <div class="text-xs text-text-secondary mb-4 p-2 bg-surface-secondary rounded">
            <p class="mb-1"><strong>Struktur:</strong> Pilih Kategori lalu klik <strong>Tambah Keterangan</strong> untuk
                mengisi satu atau banyak keterangan dalam kategori yang sama.</p>
            <p>Kategori <span class="text-success font-semibold">Pemasukan</span> otomatis menjadi
                <strong>Jumlah Pemasukan</strong>, kategori <span class="text-error font-semibold">Pengeluaran</span>
                otomatis menjadi <strong>Jumlah Pengeluaran</strong>.</p>
            <p class="mt-1">Hapus blok keterangan untuk menghapus bon, atau hapus kategori untuk menghapus seluruh
                keterangannya.</p>
            <p class="mt-1 text-warning"><i class="fa-solid fa-lock"></i> Transaksi otomatis dari Bukti Pembayaran, Upah
                Kerja (Payroll), dan Kasbon Divisi tidak dapat dihapus di sini — hapus lewat modul sumbernya (Bukti
                Pembayaran, Payroll, atau Kasbon).</p>
        </div>
    </div>

    @if ($existingItems->isEmpty())
        <p id="emptyTransactionsHint-{{ $recap->id }}" class="text-sm text-text-secondary mb-3">
            Belum ada transaksi. Klik "Tambah Kategori" di bawah untuk menambahkan.
        </p>
    @endif

    {{-- Container Transaksi (terisi otomatis dari transaksi existing) --}}
    <div id="transactionsContainer-{{ $recap->id }}" class="space-y-4 mb-3"
        data-categories="{{ $categoriesJson }}"
        data-existing-items="{{ $existingItemsJson }}"
        data-remaining-amount="{{ $recap->getRemainingAmount() }}"
        data-remaining-amount-base="{{ $recap->getRemainingAmount() }}"
        data-original-total-rab="{{ $recap->total_rab }}"></div>

    <div id="transactionsContainer-{{ $recap->id }}-incomeWarning"
        class="hidden mb-3 p-3 bg-error-light border-2 border-error rounded text-sm text-error font-medium"></div>

    <button type="button" onclick="addTransactionCategoryGroup('transactionsContainer-{{ $recap->id }}')"
        class="btn btn-outline-primary w-full">
        <i class="fa-solid fa-plus"></i> Tambah Kategori
    </button>

    <hr class="my-4">

    {{-- ==================== Penanda Tangan (dari Data Petinggi) ==================== --}}
    <div class="mb-3">
        <h6 class="text-text-primary font-semibold mb-3">Penanda Tangan</h6>
        <p class="text-xs text-text-secondary mb-3">Opsional — pilih petinggi sebagai penandatangan laporan. Data
            diambil dari modul Data Petinggi; jika dikosongkan, blok tanda tangan pada cetakan PDF/Excel tidak
            menampilkan nama.</p>

        @php
            $signatureRoles = [
                'mandor' => 'Mandor',
                'kabag_keuangan' => 'Kabag Keuangan',
                'direktur' => 'Direktur PT. Aghitsna Karya Indah',
            ];
            $storedSignatures = is_array($reportSignatures) ? $reportSignatures : [];
        @endphp

        <div class="grid grid-cols-1 md:grid-cols-3 gap-3">
            @foreach ($signatureRoles as $roleKey => $roleLabel)
                <x-forms.searchable-select
                    name="signatures[{{ $roleKey }}]"
                    id="signatures-{{ $roleKey }}-{{ $recap->id }}"
                    :label="$roleLabel"
                    placeholder="Cari petinggi..."
                    :options="$executiveOptions"
                    :selected="($storedSignatures[$roleKey]['id'] ?? '')" />
            @endforeach
        </div>
    </div>

    <hr class="my-4">

    {{-- Total Keseluruhan --}}
    <div class="flex justify-end mb-3">
        <div class="bg-surface-secondary border-2 border-border-strong rounded p-4 w-full">
            <div class="space-y-2">
                <div class="flex justify-between text-sm text-text-heading border-b border-border-strong pb-2">
                    <span><strong>Total Pemasukan:</strong></span>
                    <span id="transactionsContainer-{{ $recap->id }}-totalIncome" class="font-semibold">Rp 0</span>
                </div>
                <div class="flex justify-between text-sm text-text-heading border-b border-border-strong pb-2">
                    <span><strong>Total Pengeluaran:</strong></span>
                    <span id="transactionsContainer-{{ $recap->id }}-totalExpense" class="font-semibold">Rp 0</span>
                </div>
                <div class="flex justify-between text-lg text-text-heading">
                    <span><strong>Saldo:</strong></span>
                    <p class="font-bold text-2xl text-text-heading"><span
                            id="transactionsContainer-{{ $recap->id }}-balance">Rp 0</span></p>
                </div>
            </div>
        </div>
    </div>
</x-modal>
