<?php

namespace App\Http\Controllers\Report;

use App\Http\Controllers\Controller;
use App\Models\Report\ExpenseReport;
use App\Models\TransactionCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;

class ExpenseReportController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $search = $request->get('search');
        $month = $request->get('month');
        $year = $request->get('year');
        $category = $request->get('category');

        $expenseReports = ExpenseReport::query()
            ->with(['category', 'salesReport', 'creator'])
            ->when($search, function ($query, $search) {
                return $query->where('id', 'like', "%{$search}%")
                    ->orWhere('description', 'like', "%{$search}%")
                    ->orWhere('invoice_number', 'like', "%{$search}%");
            })
            ->when($category, function ($query, $category) {
                return $query->where('transaction_category_id', $category);
            })
            ->when($month, function ($query, $month) {
                return $query->whereMonth('transaction_date', $month);
            })
            ->when($year, function ($query, $year) {
                return $query->whereYear('transaction_date', $year);
            })
            ->orderBy('transaction_date', 'desc')
            ->orderBy('created_at', 'desc')
            ->paginate(10);

        // Get all categories for dropdown
        $categories = TransactionCategory::active()->orderBy('sort_order')->get();

        // Calculate totals with filters
        $totals = ExpenseReport::query()
            ->when($category, function ($query, $category) {
                return $query->where('transaction_category_id', $category);
            })
            ->when($month, function ($query, $month) {
                return $query->whereMonth('transaction_date', $month);
            })
            ->when($year, function ($query, $year) {
                return $query->whereYear('transaction_date', $year);
            })
            ->select(
                DB::raw('SUM(income_amount) as total_income'),
                DB::raw('SUM(expense_amount) as total_expense')
            )->first();

        $totals->balance = ($totals->total_income ?? 0) - ($totals->total_expense ?? 0);

        return view('pages.report.expense-report', compact('expenseReports', 'categories', 'totals'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'transaction_category_id' => 'required|exists:transaction_categories,id',
            'transaction_date' => 'required|date',
            'description' => 'required|string|max:1000',
            'expense_amount' => 'required|integer|min:0',
            'invoice_number' => 'nullable|string|max:100',
            'money_source' => 'nullable|string|max:255',
            'notes' => 'nullable|string',
        ], [
            'transaction_category_id.required' => 'Kategori pengeluaran wajib dipilih',
            'transaction_date.required' => 'Tanggal wajib diisi',
            'description.required' => 'Keterangan wajib diisi',
            'expense_amount.required' => 'Jumlah pengeluaran wajib diisi',
            'expense_amount.integer' => 'Jumlah pengeluaran harus berupa angka',
            'expense_amount.min' => 'Jumlah pengeluaran tidak boleh negatif',
        ]);

        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }

        $validated = $validator->validated();
        $validated['created_by'] = Auth::id();
        $validated['income_amount'] = null;

        try {
            ExpenseReport::create($validated);

            return redirect()->route('expense-report.index')
                ->with('success', 'Data laporan pengeluaran berhasil ditambahkan!');
        } catch (\Exception $e) {
            return back()->with('error', 'Terjadi kesalahan: ' . $e->getMessage())->withInput();
        }
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $expenseReport = ExpenseReport::findOrFail($id);

        // Cek apakah ini auto-generated (tidak boleh edit yang auto-generated dari sales report)
        if ($expenseReport->isAutoGenerated()) {
            return back()->with('error', 'Data yang auto-generated dari sales report tidak dapat diubah!');
        }

        $validator = Validator::make($request->all(), [
            'transaction_category_id' => 'required|exists:transaction_categories,id',
            'transaction_date' => 'required|date',
            'description' => 'required|string|max:1000',
            'expense_amount' => 'required|integer|min:0',
            'invoice_number' => 'nullable|string|max:100',
            'money_source' => 'nullable|string|max:255',
            'notes' => 'nullable|string',
        ], [
            'transaction_category_id.required' => 'Kategori pengeluaran wajib dipilih',
            'transaction_date.required' => 'Tanggal wajib diisi',
            'description.required' => 'Keterangan wajib diisi',
            'expense_amount.required' => 'Jumlah pengeluaran wajib diisi',
        ]);

        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }

        $validated = $validator->validated();

        try {
            $expenseReport->update($validated);

            return redirect()->route('expense-report.index')
                ->with('success', 'Data laporan pengeluaran berhasil diupdate!');
        } catch (\Exception $e) {
            return back()->with('error', 'Terjadi kesalahan: ' . $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $expenseReport = ExpenseReport::findOrFail($id);

        // Cek apakah ini auto-generated (tidak boleh hapus yang auto-generated dari sales report)
        if ($expenseReport->isAutoGenerated()) {
            return back()->with('error', 'Data yang auto-generated dari sales report tidak dapat dihapus!');
        }

        try {
            $expenseReport->delete();

            return redirect()->route('expense-report.index')
                ->with('success', 'Data laporan pengeluaran berhasil dihapus!');
        } catch (\Exception $e) {
            return back()->with('error', 'Terjadi kesalahan: ' . $e->getMessage());
        }
    }

    /**
     * Delete selected items (bulk delete).
     */
    public function destroySelected(Request $request)
    {
        $selectedIds = $request->input('selected_expenses', []);

        if (empty($selectedIds)) {
            return back()->with('error', 'Tidak ada data yang dipilih!');
        }

        try {
            $expenseReports = ExpenseReport::whereIn('id', $selectedIds)->get();
            $deletedCount = 0;
            $skippedCount = 0;

            foreach ($expenseReports as $expenseReport) {
                // Skip auto-generated data
                if ($expenseReport->isAutoGenerated()) {
                    $skippedCount++;
                    continue;
                }

                $expenseReport->delete();
                $deletedCount++;
            }

            $message = "Berhasil menghapus {$deletedCount} data.";
            if ($skippedCount > 0) {
                $message .= " {$skippedCount} data auto-generated dilewati.";
            }

            return redirect()->route('expense-report.index')
                ->with('success', $message);
        } catch (\Exception $e) {
            return back()->with('error', 'Terjadi kesalahan: ' . $e->getMessage());
        }
    }

    /**
     * Export expense report to Excel
     */
    public function exportExcel(Request $request)
    {
        // TODO: Implement Excel export
        return back()->with('info', 'Fitur export Excel sedang dalam pengembangan');
    }

    /**
     * Export expense report to PDF
     */
    public function exportPdf(Request $request)
    {
        // TODO: Implement PDF export
        return back()->with('info', 'Fitur export PDF sedang dalam pengembangan');
    }
}
