@extends('layouts.app')

@section('title', 'PT Aghitsna Karya Indah - Rekap Pengeluaran')

@section('content')
    <div class="bg-surface-base p-4 sm:p-6 rounded-xl shadow">
        {{-- Header Rekap Pengeluaran --}}
        <h1 class="text-2xl font-semibold text-text-primary mb-4">Rekap Pengeluaran</h1>

        {{-- Toolbar: Filter + Action Buttons --}}
        <div class="mb-4 flex items-center justify-between flex-wrap gap-3">
            {{-- Form Pencarian dan Filter --}}
            <form method="GET" action="{{ route('recap-expense.index') }}"
                class="w-full lg:w-auto lg:flex-1 flex flex-col lg:flex-row gap-3">

                {{-- Filter Kategori --}}
                <x-filters.select-filter name="category" :value="request('category')" :options="$categories" placeholder="Semua Kategori" />

                {{-- Filter Bulan --}}
                <x-filters.month-filter :value="request('month')" />

                {{-- Filter Tahun --}}
                <x-filters.year-filter :value="request('year')" />

                {{-- Search Input --}}
                <x-filters.search-input :value="request('search')" placeholder="Cari transaksi..." />
            </form>

            {{-- Aksi di Kanan --}}
            <div class="flex items-center gap-2 mt-2 lg:mt-0 w-full lg:w-auto">
                <div class="flex flex-col sm:flex-row gap-2 w-full lg:w-auto">
                    {{-- Tombol Export --}}
                    <x-buttons.print-dropdown :excelRoute="route('recap-expense.export.excel')" :pdfRoute="route('recap-expense.export.pdf')" :queryParams="[
                        'search' => request('search'),
                        'category' => request('category'),
                        'month' => request('month'),
                        'year' => request('year'),
                    ]" />

                    {{-- Tombol Hapus --}}
                    <x-buttons.delete-button modalId="deleteModal" />

                    {{-- Tombol Tambah --}}
                    <x-buttons.add-button modalId="addModal" text="Tambah Pengeluaran" />
                </div>
            </div>
        </div>

        {{-- Tabel Rekap Pengeluaran --}}
        @include('components.finance.expense-recaps.table', [
            'expenseRecaps' => $expenseRecaps,
            'totals' => $totals,
        ])
    </div>

    {{-- Pagination --}}
    <x-pagination :paginator="$expenseRecaps" />

    {{-- Modal Tambah --}}
    @include('components.finance.expense-recaps.add-modal', ['categories' => $categories])

    {{-- Modal Edit untuk setiap expense (hanya yang manual) --}}
    @foreach ($expenseRecaps as $expense)
        @if (!$expense->isAutoGenerated())
            @include('components.finance.expense-recaps.edit-modal', ['expense' => $expense, 'categories' => $categories])
        @endif
    @endforeach

    {{-- Modal Hapus --}}
    <x-modal id="deleteModal" title="Konfirmasi Hapus" :confirmDelete="true" onConfirm="submitDeleteForm()"
        buttonText="Ya, Hapus">
        <p class="text-text-primary mb-4">Apakah Anda yakin ingin menghapus data yang dipilih?</p>
        <p class="text-sm text-text-secondary">
            <i class="fa-solid fa-info-circle"></i> Data yang auto-generated dari sales report tidak akan dihapus.
        </p>
    </x-modal>

    {{-- JavaScript --}}
    @vite(['resources/js/pages/finance/expense-recaps/index.js'])
@endsection
