<?php

namespace App\Http\Controllers\Sdm;

use App\Http\Controllers\Controller;
use App\Http\Requests\Sdm\StoreEmployeeRequest;
use App\Http\Requests\Sdm\UpdateEmployeeRequest;
use App\Models\Sdm\Employee;
use App\Services\Sdm\EmployeeService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

/**
 * Controller for managing employee data.
 *
 * Handles HTTP requests and responses for employee CRUD operations.
 * Business logic is delegated to EmployeeService.
 */
class EmployeeController extends Controller
{
    /**
     * The employee service instance.
     *
     * @var EmployeeService
     */
    protected EmployeeService $employeeService;

    /**
     * Create a new controller instance.
     *
     * @param  EmployeeService  $employeeService
     */
    public function __construct(EmployeeService $employeeService)
    {
        $this->employeeService = $employeeService;
    }

    /**
     * Display a paginated list of employees with optional search.
     *
     * @param  Request  $request
     * @return View
     */
    public function index(Request $request): View
    {
        $search = $request->input('search');
        $employees = $this->employeeService->getPaginatedEmployees($search);
        $divisions = $this->employeeService->getAllDivisions();

        return view('pages.human-resource.employees.index', compact('employees', 'search', 'divisions'));
    }

    /**
     * Store a newly created employee in storage.
     *
     * The employee_code is auto-generated by the service.
     * The daily_wage is already normalized by the form request.
     *
     * @param  StoreEmployeeRequest  $request
     * @return RedirectResponse
     */
    public function store(StoreEmployeeRequest $request): RedirectResponse
    {
        $this->employeeService->createEmployee($request->validated());

        return redirect()->route('employee.index')
            ->with('success', 'Data karyawan berhasil ditambahkan!');
    }

    /**
     * Update the specified employee in storage.
     *
     * @param  UpdateEmployeeRequest  $request
     * @param  \App\Models\Sdm\Employee  $employee
     * @return RedirectResponse
     */
    public function update(UpdateEmployeeRequest $request, Employee $employee): RedirectResponse
    {
        $this->employeeService->updateEmployee($employee, $request->validated());

        return redirect()->route('employee.index')
            ->with('success', 'Data karyawan berhasil diperbarui!');
    }

    /**
     * Remove the specified employees from storage (bulk delete).
     *
     * @param  Request  $request
     * @return RedirectResponse
     */
    public function destroy(Request $request): RedirectResponse
    {
        $ids = $request->input('ids');

        if (empty($ids)) {
            return redirect()->route('employee.index')
                ->with('error', 'Tidak ada data yang dipilih!');
        }

        $this->employeeService->deleteEmployees($ids);

        return redirect()->route('employee.index')
            ->with('success', 'Data karyawan berhasil dihapus!');
    }
}
