<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     *
     * Table: project_quotations
     * The quotation_number is the primary key with format: {seq}/{seq}/PT.AKI/{YY}
     * e.g. 1/1/PT.AKI/26, 2/2/PT.AKI/26
     * sequence_number is an auto-increment integer per year used to generate the format.
     */
    public function up(): void
    {
        Schema::create('project_quotations', function (Blueprint $table) {
            // Primary key: format "1/1/PT.AKI/26" — generated by the app
            $table->string('quotation_number')->primary();

            // Sequence number per year (used to auto-generate quotation_number)
            $table->unsignedInteger('sequence_number');

            $table->date('date');                               // Tanggal
            $table->string('subject')->default('Penawaran Harga'); // Hal
            $table->string('recipient');                        // Kepada Yth
            $table->string('recipient_address')->default('Ditempat'); // Ditempat / Alamat

            $table->bigInteger('total_amount');                 // Grand total
            $table->string('amount_in_words')->nullable();      // Terbilang

            // Selected bank accounts (many), stored as JSON array of payment_accounts.id
            $table->json('selected_payment_accounts')->nullable();

            $table->string('signed_by')->nullable();            // e.g. Akhmad Khaidir
            $table->string('division')->nullable();             // e.g. Divisi Alumunium

            $table->timestamps();

            // Unique: one sequence_number per calendar year
            $table->unique(['sequence_number', 'date']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('project_quotations');
    }
};
