{{-- =====================================================================
     Partial Tab: Rekap Pengeluaran (dipakai pada halaman Rekap tab pengeluaran)
     Data tersedia dari RecapExpenseController::indexData():
     - $expenseRecaps : Paginator ExpenseRecap (10/halaman)
     - $categories    : Daftar kategori pengeluaran (filter & dropdown modal)
     - $totals        : Grand totals (income, expense, balance)
     ===================================================================== --}}

    <div class="bg-surface-base p-4 sm:p-6 rounded-xl shadow">
        {{-- Header Rekap Pengeluaran --}}
        <h1 class="text-2xl font-semibold text-text-primary mb-4">Rekap Pengeluaran</h1>

        {{-- Toolbar: Filter + Action Buttons (form mengarah ke tab aktif) --}}
        <div class="mb-4 flex items-center justify-between flex-wrap gap-3">
            <form method="GET" action="{{ route('rekap.index', ['tab' => 'pengeluaran']) }}"
                class="w-full min-[1520px]:w-auto min-[1520px]:flex-1 flex flex-col min-[1520px]:flex-row gap-3">

                <x-filters.select-filter name="category" :value="request('category')" :options="$categories" placeholder="Semua Kategori" responsive="custom" />
                <x-filters.month-filter :value="request('month')" responsive="custom" />
                <x-filters.year-filter :value="request('year')" responsive="custom" />
                <x-filters.search-input :value="request('search')" placeholder="Cari transaksi..." responsive="custom" />
            </form>

            <div class="flex items-center gap-2 mt-2 min-[1520px]:mt-0 w-full min-[1520px]:w-auto">
                <div class="flex flex-col min-[1520px]:flex-row gap-2 w-full min-[1520px]:w-auto">
                    <x-buttons.print-dropdown :excelRoute="route('recap-expense.export.excel')" :pdfRoute="route('recap-expense.export.pdf')" :queryParams="[
                        'search' => request('search'),
                        'category' => request('category'),
                        'month' => request('month'),
                        'year' => request('year'),
                    ]" responsive="custom" />

                    <x-buttons.delete-button modalId="deleteModal" responsive="custom" />
                    <x-buttons.add-button modalId="addModal" text="Tambah Pengeluaran" responsive="custom" />
                </div>
            </div>
        </div>

        {{-- Tabel Rekap Pengeluaran --}}
        @include('components.finance.expense-recaps.table', [
            'expenseRecaps' => $expenseRecaps,
            'totals' => $totals,
        ])
    </div>

    {{-- Pagination --}}
    <x-pagination :paginator="$expenseRecaps" />

    {{-- Modal Tambah --}}
    @include('components.finance.expense-recaps.add-modal', ['categories' => $categories])

    {{-- Modal Edit untuk setiap expense (hanya yang manual) --}}
    @foreach ($expenseRecaps as $expense)
        @if (!$expense->isAutoGenerated())
            @include('components.finance.expense-recaps.edit-modal', ['expense' => $expense, 'categories' => $categories])
        @endif
    @endforeach

    {{-- Modal Konfirmasi Bulk Delete --}}
    <x-modal id="deleteModal" title="Konfirmasi Hapus" :confirmDelete="true" onConfirm="submitDeleteForm()"
        buttonText="Ya, Hapus">
        <p class="text-text-primary mb-4">Apakah Anda yakin ingin menghapus data yang dipilih?</p>
        <p class="text-sm text-text-secondary">
            <i class="fa-solid fa-info-circle"></i> Data yang auto-generated dari sales report tidak akan dihapus.
        </p>
    </x-modal>

    @push('scripts')
        @vite(['resources/js/pages/finance/expense-recaps/index.js'])
    @endpush